-- 21-div.sql
DROP FUNCTION IF EXISTS SafeDiv;
DELIMITER $$

CREATE FUNCTION SafeDiv(a INT, b INT)
RETURNS DOUBLE
DETERMINISTIC
BEGIN
    RETURN CASE
        WHEN b = 0 THEN 0
        ELSE ROUND(a / b, 6)
    END;
END$$

DELIMITER ;
