DROP FUNCTION IF EXISTS SafeDiv;
DELIMITER $$

CREATE FUNCTION SafeDiv(a INT, b INT)
RETURNS DOUBLE
DETERMINISTIC
BEGIN
    RETURN ROUND(
        CASE
            WHEN b = 0 THEN 0
            ELSE a / b
        END,
        6
    );
END$$

DELIMITER ;
